import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Main.module.css'
import { NavHeader } from "../components/navheader"
import { Footer } from '../components/footer'
import { Button } from '../components/button';
import { SignIn } from '../components/signin';
import { getSignedIn, init, setSignedIn } from '../lib/networkmanager';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Tome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-3/5 ml-8 pt-48">
          <h1 className="text-5xl pb-2">Tome | Your place for stories</h1>
          <p className='text-2xl pl-1'>Explore stories, worldbuilding, essays and more from fantastic creators.</p>
          <SignIn className="pl-1 ml-1 mt-4" textClassName="text-4xl p-1" signOut={false}></SignIn>
        </div>
      </main>
    </>
  )
}

export default Home
