import { NextPage } from "next"
import Head from "next/head"
import Router, { useRouter } from "next/router"
import { getProfile, onDefaultProfile, getProfilePosts, isAdmin } from '../lib/networkmanager';
import { useEffect } from 'react';
import { PostCard } from "../components/postcard";
import { ObjectId } from "mongodb";


let timer: any, found: boolean = false
async function checkDefault(): Promise<any> {
    clearInterval(timer)
    console.log(Router.query.user)
    if((Router.query.user === null || Router.query.user === undefined || Router.query.user === "null") && !found) onDefaultProfile()
}

const Profile: NextPage = () => {
    const user = useRouter().query.user
    let posts: string | any[] | null | undefined = []
    if(useRouter().query.posts !== undefined) posts = JSON.parse(useRouter().query.posts as string)

    useEffect(() => {
        console.log("User: " + user)
        if(Router.query.user === null || Router.query.user === undefined || Router.query.user === "null") {
            console.log("Setting timer for checkDefault")
            timer = setInterval(checkDefault, 100)
        }
        else {
            found = true
            console.log(Router.query)
            if(Router.query.posts === undefined) {
                posts = []
                getProfilePosts(user as string)
            }
            else {
                getProfile(String(user))
                if(Router.query.posts !== undefined) posts = JSON.parse(Router.query.posts as string)
            }
        }
    })

    return (
        <>
            <Head>
                <title id="pageTitle">Profile | Tome</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pl-4 pt-4">
                <h1 id="username" className="text-4xl">Username</h1> <span className="italic" id="time"></span>
                <p id="bio"></p>
                <h1 id="username" className="text-2xl">Posts</h1>
                <div>
                    {(posts !== undefined) && (posts! as any[]).reverse().map((value, index) => {
                        return <PostCard title={value.title} body={value.body} thumbnail={value.thumbnail} 
                            id={value._id as ObjectId} views={value.views} likes={value.likes} dislikes={value.dislikes} author={value.owner}></PostCard>
                    })}
                </div>
            </main>
        </>
    )
}

export default Profile